
# Dockerfile para Desarrollo para que no vaya por nginx 
# y si hay cambios en la web en tiempò real al programar

FROM node:20-alpine AS dev

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 3000

# Servidor Astro con hot reload
CMD ["npm","run","dev","--","--host","0.0.0.0","--port","3000"]
