services:
  db:
    image: postgres:16
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - redroosters_audio:/app/uploads/audio

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      BACK_PORT: ${BACK_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      AUDIO_DIR: /app/uploads/audio
      TZ: Europe/Madrid
      # Para detectar la hora correcta
      JAVA_TOOL_OPTIONS: -Duser.timezone=Europe/Madrid
    volumes:
      - redroosters_audio:/app/uploads/audio
      - redroosters_portadas:/app/uploads/portadas
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      PUBLIC_API_URL: "${PUBLIC_API_URL}"
      PUBLIC_BACKEND_URL: "${PUBLIC_BACKEND_URL}"
      BACKEND_INTERNAL_URL: "${BACKEND_INTERNAL_URL}"
    depends_on:
      - backend

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template:ro
      - ./certbot/www:/var/www/certbot
      - redroosters_audio:/app/uploads/audio:ro
      - redroosters_portadas:/app/uploads/portadas:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  redroosters_audio:
  redroosters_portadas:


