# Todo lo que llegue por HTTP se redirige a HTTPS
server {
  listen 80;
  listen [::]:80;
  server_name redroosterstv.com www.redroosterstv.com;

  # Ruta para las renovaciones automáticas de Certbot
  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

# Servidor principal HTTPS
server {
  # Nginx escuha por el 443
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name redroosterstv.com www.redroosterstv.com;

  # Certificados de Let's Encrypt (dentro del contenedor, montados desde /etc/letsencrypt del host)
  ssl_certificate     /etc/letsencrypt/live/redroosterstv.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/redroosterstv.com/privkey.pem;

  # Configuración de cifrado seguro SSL/TLS
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;


  # Contenedor frontend Astro
  location / {
    #proxy_pass http://frontend:3000;
    proxy_pass http://frontend:80;
    proxy_http_version 1.1;

    # Mantiene la información real del cliente (dominio, IP y protocolo) cuando nginx renvia la peticional frontend
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # Contenedor backend Spring
  location /api/ {
    proxy_pass http://backend:9000;
    proxy_http_version 1.1;

    # Mantiene la información real del cliente (dominio, IP y protocolo) cuando nginx renvia la peticional frontend
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Soportar subidas de archivos grandes (audios)
    client_max_body_size 100m;
    proxy_request_buffering off;

    # Cabecera de autorizacion para JWT
    proxy_set_header Authorization $http_authorization;

  }

  # Proxy para servir las imágenes y audios subidos
location /uploads/ {
    proxy_pass http://backend:9000/uploads/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}

}